### PR TITLE
Adding symfony_console_path variable to make app/console path configu…

### PR DESCRIPTION
**Pull request by gtrias**
Adding symfony_console_path variable to make app/console path configurable refs cbrunnkvist/ansistrano-symfony-deploy#10

### CODE REVIEW

**Comment by gtrias** [comment]
I'm not used to testing ansible playbooks. I don't know why the tests are failing. Any tip on how I can fix it?
Shouldn't test get the default variables? 
The changes works for me to deploy symfony3 projects and symfony <3  as well...

**Comment by raul782** [comment]
@gtrias This is due to Travis using ansible 2, which has an issue that is already solved by the following PR https://github.com/cbrunnkvist/ansistrano-symfony-deploy/pull/9

@cbrunnkvist, if merged in that order, we should be good to go, and be able to deploy symfony3 apps.

**Comment by gtrias** [comment]
btw I'm not sure this project is already maintained since the pull requests and commits has no responses since July. I've forked it in order to apply the pull requests by myself and keep it using.

**Comment by raul782** [comment]
@gtrias That's true, it's too bad, since I believe this is a good project and needs to keep evolving,
I'll use your fork now thanks.

**Comment by cbrunnkvist** [comment]
Wow, I have PRs?! I had to turn off notifications, so I had not noticed! 

But please - go ahead and use @gtrias fork if you need it. The power of Github! 👍 

My day job has had me change my main web development tech stack, hence I do not have time and/or any realistic use cases for maintaining Symfony-related things I'm afraid.

**Pull request merged**
