### PR TITLE
Add option Env variables for composer install

### PR DESCRIPTION
**Pull request by jycamier**

### CODE REVIEW

**Comment by cbrunnkvist** [comment]
Cool, we have a Travis job? I even forgot that I set it up. 

❤️CI❤️

I don't have any way of checking this so I will hand it over to a new maintainer ~ 🎉

**Comment by scuben** [comment]
Hi @eheuje, I finally have time to review this PR. I'm not sure this is a feature that should be part of ansistrano-symfony-deploy. If you have env vars you might want to just use `'%env(DATABASE_HOST)%'` in your config or parameters file. WDYT?

**Comment by piotrkochan** [comment]
@scuben yeah but if You're using older Symfony version this setting is very helpful

**Comment by jycamier** [comment]
> @scuben yeah but if You're using older Symfony version this setting is very helpful

To use this feature (https://github.com/Incenteev/ParameterHandler#using-environment-variables-to-set-the-parameters), you don't need a specific parameter to do it. It was a misktake. You can do it like that : 

```yaml
---
- hosts: all
  gather_facts: false
  environment:
    DATABASE_HOST: "{{database_host}}"
    DATABASE_NAME: "{{database_name}}"
    DATABASE_USER: "{{database_user}}"
    DATABASE_PASSWORD: "{{database_password}}"
  vars:
    ansistrano_deploy_from: ../my-project-checkout
    ansistrano_deploy_to: /home/app-user/my-project-deploy/
    ansistrano_before_symlink_tasks_file: "{{playbook_dir}}/config/app_specific_setup.yml"
  roles:
    - cbrunnkvist.ansistrano-symfony-deploy

```
Then, you put your variables in **host_vars**/ or **group_vars**/, depending of your project(s) : look at the precedences of vars.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

Don't forget to use Ansible Vault.

https://docs.ansible.com/ansible/latest/user_guide/vault.html

**Comment by scuben** [comment]
Thank you for the update. I'll close it then.

**Pull request closed without merging**
